### ISSUE TITLE
REST 問題を作る

### ISSUE THREAD

**Issue by elzup** [elzup/AtColor#2]
アイデアあれば下さい

/question/:id で解いていく感じにします。

- [x] 1, title: 'can you GET?', description: '自分のプロフィールを取得する。', 
- [x] 2, title: 'can you POST?', description: 'ユーザを作成する。', 
- [x] 3, title: 'can you PUT?', description: '自分のプロフィールを更新する。', 

- [x] 4, title: 'can you DELETE?', description: '/q/4 に DELETE リクエストを送る。', 

- [x] 5, title: 'can you set headers?', description: 'GET /q/5', 
- [x] 6, title: 'can you get headers?', description: 'GET /q/6', 

- [x] 7, title: 'can you get next page?', description: 'GET /q/7', 
- [ ] 8, title: 'can you get last page?', description: 'GET /q/8', 

- [x] 9, title: 'can you timestamp?', description: 'POST /q/9', 
- [ ] 10, title: 'can you resend?', description: 'POST /q/10', 

- [ ] 101, title: 'can you find me?', description: '???', 
- [ ] 102, title: 'are you backend developer?', description: '???', 
- [ ] 103, title: 'are you frontend developer?', description: '???', 
- [ ] 104, title: 'are you designer?', description: '???',

**Comment by nshiba** [comment]
> header 設定出来る authorization

これなんか設定できてるかどうかのendpoint生やしたりできます?
今 `/pixels` しかないのでこれでもいんだけど、あったほうが説明が楽

**Comment by elzup** [comment]
@nshiba 了解です `/q/` などに別で用意します。

**Comment by nshiba** [comment]
thanks

**Comment by elzup** [comment]
https://github.com/elzup/AtColor/blob/master/app/models/question.rb
